env = "local"
app_name = "example"
debug = "off"
storage_path = "./storage/"
token_secret = "abcdefghijklmnop"

[database]
    [database.default]
    enable = true
    driver = "mysql"
    dsn = "root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8&parseTime=True&loc=Asia%2FShanghai"
    max_open_conns= 10
    max_idle_conns = 5
    show_sql = false

[redis]
    [redis.default]
    server = ""
    password = ""
    db = 0