env = "local"
app_name = "example"
debug = "off"
storage_path = "./storage/"

[log]
    log_mode = "file"
    log_path = "./storage/logs/"
    log_format = "json"
    log_level = "info"
    log_max_files = 15
    log_sentry_dsn = ""
    log_sentry_type = "go"
    log_detail = true

[database]
    [database.default]
    enable = true
    driver = "mysql"
    dsn = ""
    max_open_conns= 10
    max_idle_conns = 5
    show_sql = false

[redis]
    [redis.default]
    server = ""
    password = ""
    db = 0